[package]
name = "generic_data_types_and_error_handling"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.11.4"


[[target.executable]]
name = "generic_data_types_and_error_handling"
function = "generic_data_types_and_error_handling::generic_data_types_and_error_handling::main"



